############################
# FONT
############################

font_family      JetBrainsMono Nerd Font
font_size        16.0


############################
# SHELL
############################

shell /usr/bin/zsh
shell_integration no-cursor

############################
# WINDOW / PADDING
############################

window_padding_width 10
placement_strategy center
remember_window_size  yes
initial_window_width  100c
initial_window_height 30c

############################
# TRANSPARENCY
############################

background_opacity 0.9

############################
# TOKYO NIGHT COLORS
############################

foreground #c0caf5
background #1a1b26

# Black
color0  #15161e
color8  #414868

# Red
color1  #f7768e
color9  #f7768e

# Green
color2  #9ece6a
color10 #9ece6a

# Yellow
color3  #e0af68
color11 #e0af68

# Blue
color4  #7aa2f7
color12 #7aa2f7

# Magenta
color5  #bb9af7
color13 #bb9af7

# Cyan
color6  #7dcfff
color14 #7dcfff

# White
color7  #a9b1d6
color15 #c0caf5

############################
# CURSOR
############################

cursor              #c0caf5
cursor_text_color   #1a1b26
cursor_shape beam
cursor_beam_thickness 2
cursor_trail 300
cursor_trail_decay 0.3 0.5
cursor_blink_interval 0
cursor_trail_start_threshold 2

repaint_delay 8
input_delay 2
sync_to_monitor yes


############################
# SELECTION
############################

selection_foreground none
selection_background #28344a

############################
# URL COLOR
############################

url_color #9ece6a

############################
# WINDOW BORDERS
############################

active_border_color   #3d59a1
inactive_border_color #101014
bell_border_color     #e0af68

############################
# TAB BAR
############################

tab_bar_style fade
tab_fade 1

active_tab_foreground   #3d59a1
active_tab_background   #16161e
active_tab_font_style   bold

inactive_tab_foreground #787c99
inactive_tab_background #16161e
inactive_tab_font_style bold

tab_bar_background #101014
