
# █▀▄▀█ █▀█ █▄ █ █ ▀█▀ █▀█ █▀█
# █ ▀ █ █▄█ █ ▀█ █  █  █▄█ █▀▄

monitor = ,1920x1080@144,auto,1


# █▀▄▀█ █ █▀ █▀▀
# █ ▀ █ █ ▄█ █▄▄

$terminal = kitty
$fileManager = thunar
$fileManagerT = kitty -e yazi
$menu = rofi -show drun
$reload_waybar = pkill waybar && waybar &


# █   ▄▀█ █ █ █▄ █ █▀▀ █ █
# █▄▄ █▀█ █▄█ █ ▀█ █▄▄ █▀█

exec-once = waybar 
exec-once = swww-daemon
exec-once = swaync
exec-once = blueman-applet
exec-once = hypridle
exec-once =  kwybars-daemon --config ~/.config/kwybars/custom/my_config.toml &
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = swayosd-server &



# █▀▀ █▄ █ █ █
# ██▄ █ ▀█ ▀▄▀

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,18



# █   ▄▀█ █▄█ █▀█ █ █ ▀█▀ █▀
# █▄▄ █▀█  █  █▄█ █▄█  █  ▄█

dwindle {
    pseudotile = true
    preserve_split = true 
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

# █ █▄ █ █▀█ █ █ ▀█▀
# █ █ ▀█ █▀▀ █▄█  █

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}
gesture = 3, horizontal, workspace
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# █▀ █▀█ █ █ █▀█ █▀▀ █▀▀
# ▄█ █▄█ █▄█ █▀▄ █▄▄ ██▄

source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/windowrules.conf
# source = ~/.config/hypr/nvidia.conf


