# BACKGROUND
background {
    monitor =
    path = ~/.config/hypr/hyprlock.png
    blur_passes = 4
    blur_size = 8
    brightness = 0.75
    contrast = 1.05
}

# GENERAL
general {
    no_fade_in = false
    grace = 2
    disable_loading_bar = true
}

# AVATAR
image {
    monitor =
    path = ~/.config/hypr/profile.jpg

    size = 150
    rounding = -1

    border_size = 3
    border_color = rgba(187,154,247,0.9)

    halign = center
    valign = center
    position = 0, 80
}

# USERNAME
label {
    monitor =
    text = Aditya

    color = rgba(230,233,255,1)
    font_size = 28
    font_family = SF Pro Display Bold

    halign = center
    valign = center
    position = 0, -30
}

# PASSWORD
input-field {
    monitor =

    size = 260, 50
    outline_thickness = 2

    dots_size = 0.28
    dots_spacing = 0.25
    dots_center = true

    inner_color = rgba(28,32,50,0.85)
    outer_color = rgba(187,154,247,0.9)

    font_color = rgba(240,242,255,1)
    font_family = SF Pro Display Medium

    placeholder_text = Enter Password

    hide_input = false
    fade_on_empty = false
    rounding = 12

    halign = center
    valign = center
    position = 0, -110
}