# █▄░█ █░█ █ █▀▄ █ ▄▀█
# █░▀█ ▀▄▀ █ █▄▀ █ █▀█

env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_VRR_ALLOWED,1
env = NVD_BACKEND,direct

# card2 = RTX 3050, card1 = Intel iGPU
env = AQ_DRM_DEVICES,/dev/dri/card2:/dev/dri/card1

cursor:no_hardware_cursors = true