############################

# FONT

############################

font_family      JetBrainsMono Nerd Font
font_size        15.0

############################

# SHELL

############################

shell /usr/bin/zsh
shell_integration no-cursor

############################

# WINDOW / PADDING

############################

window_padding_width 10
placement_strategy center
remember_window_size  yes
initial_window_width  100c
initial_window_height 30c

############################

# TRANSPARENCY

############################

background_opacity 0.5

############################

# MOON SHRINE PALETTE

# (high contrast version)

############################

foreground #f2f2f7
background #0a0a0c

# Black

color0  #0a0a0c
color8  #44444a

# Red (berries)

color1  #b2354b
color9  #e14d63

# Green (moss / forest)

color2  #7a9a7e
color10 #9dc6a1

# Yellow (moon warmth)

color3  #d9c38f
color11 #f0e2b6

# Blue (moonlight)

color4  #6f86b6
color12 #9ab3ff

# Magenta (branch tint)

color5  #8d5a70
color13 #b87a95

# Cyan (cold light)

color6  #7fa4b0
color14 #a9d4e0

# White

color7  #d9d9e0
color15 #ffffff

############################

# CURSOR

############################

cursor #ffffff
cursor_text_color #0a0a0c
cursor_shape beam
cursor_trail 1
cursor_beam_thickness 6
cursor_blink_interval 0
# cursor_trail 300
# cursor_trail_decay 0.3 0.5
# cursor_trail_start_threshold

repaint_delay 8
input_delay 2
sync_to_monitor yes

############################

# SELECTION

############################

selection_background #2a2f3a
selection_foreground #ffffff

############################

# URL

############################

url_color #9dc6a1

############################

# BORDERS

############################

active_border_color   #9ab3ff
inactive_border_color #16161a
bell_border_color     #f0e2b6


############################

# TAB BAR

############################

tab_bar_style fade
tab_fade 1

active_tab_foreground   #6a84a6
active_tab_background   #111111
active_tab_font_style   bold

inactive_tab_foreground #6c6c6c
inactive_tab_background #111111
inactive_tab_font_style bold

tab_bar_background #0b0b0c
